# Generated by Django 5.1.7 on 2025-03-29 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipments", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mode", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Vessel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                ("vessel_type", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Shipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("shipment_no", models.CharField(max_length=100, unique=True)),
                ("parcel", models.PositiveIntegerField(default=0)),
                ("weight", models.FloatField()),
                ("volume", models.FloatField()),
                ("origin", models.CharField(max_length=250)),
                ("destination", models.CharField(max_length=250)),
                ("steps", models.PositiveBigIntegerField(default=0)),
                ("document", models.PositiveBigIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_transit", "In-transit"),
                            ("delivered", "Delivered"),
                        ],
                        default="in_transit",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("customer", models.ManyToManyField(to="shipments.customer")),
                (
                    "transport",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="shipments.transport",
                    ),
                ),
                (
                    "vessel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="shipments.vessel",
                    ),
                ),
            ],
        ),
    ]
