# Generated by Django 5.1.7 on 2025-03-29 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipments", "0002_transport_vessel_shipment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shipment",
            name="transport",
            field=models.CharField(
                choices=[
                    ("air", "Air"),
                    ("sea", "Sea"),
                    ("road", "Road"),
                    ("rail", "Rail"),
                ],
                default="road",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="shipment",
            name="vessel",
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name="shipment",
            name="customer",
            field=models.ManyToManyField(
                related_name="shipments", to="shipments.customer"
            ),
        ),
        migrations.AlterField(
            model_name="shipment",
            name="status",
            field=models.CharField(
                choices=[("in_transit", "In-transit"), ("delivered", "Delivered")],
                max_length=20,
            ),
        ),
        migrations.DeleteModel(name="Transport",),
        migrations.DeleteModel(name="Vessel",),
    ]
