# Generated by Django 5.1.7 on 2025-03-31 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipments", "0003_alter_shipment_transport_alter_shipment_vessel_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="shipment", name="customer",),
        migrations.AddField(
            model_name="customer",
            name="shipment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="customers",
                to="shipments.shipment",
            ),
        ),
        migrations.AlterField(
            model_name="shipment",
            name="transport",
            field=models.CharField(
                choices=[
                    ("air", "Air"),
                    ("sea", "Sea"),
                    ("road", "Road"),
                    ("rail", "Rail"),
                ],
                max_length=100,
            ),
        ),
    ]
