# Generated by Django 5.1.7 on 2025-03-31 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipments", "0004_remove_shipment_customer_customer_shipment_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="shipment",
            name="customer_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
