# Generated by Django 5.1.7 on 2025-03-31 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipments", "0006_rename_document_shipment_document_count_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="parcel",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="customers",
                to="shipments.parcel",
            ),
        ),
    ]
