# Generated by Django 5.1.7 on 2025-03-31 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipments", "0007_customer_parcel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="shipment",
            field=models.ForeignKey(
                blank=True,
                db_column="shipment_no",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="customers",
                to="shipments.shipment",
            ),
        ),
        migrations.AlterField(
            model_name="parcel",
            name="shipment",
            field=models.ForeignKey(
                db_column="shipment_no",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="parcels",
                to="shipments.shipment",
            ),
        ),
    ]
