# Generated by Django 5.1.7 on 2025-03-31 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shipments", "0008_alter_customer_shipment_alter_parcel_shipment"),
    ]

    operations = [
        migrations.RemoveField(model_name="shipment", name="created_at",),
        migrations.RemoveField(model_name="shipment", name="updated_at",),
    ]
