# Generated by Django 5.1.7 on 2025-03-31 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipments", "0009_remove_shipment_created_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="parcel", name="customer",),
        migrations.AddField(
            model_name="parcel",
            name="customer_name",
            field=models.ForeignKey(
                blank=True,
                db_column="name",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="parcels",
                to="shipments.customer",
            ),
        ),
    ]
