# Generated by Django 5.1.7 on 2025-03-31 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipments", "0010_remove_parcel_customer_parcel_customer_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="parcel",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="parcels",
                to="shipments.customer",
            ),
        ),
        migrations.AlterField(
            model_name="parcel",
            name="customer_name",
            field=models.CharField(editable=False, max_length=255),
        ),
    ]
