# Generated by Django 5.1.7 on 2025-03-31 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipments", "0011_parcel_customer_alter_parcel_customer_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="parcel",
            field=models.ForeignKey(
                db_column="parcel_no",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="customers",
                to="shipments.parcel",
            ),
        ),
    ]
