# Generated by Django 5.1.7 on 2025-03-31 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shipments", "0012_alter_customer_parcel"),
    ]

    operations = [
        migrations.RemoveField(model_name="shipment", name="document_count",),
    ]
