# Generated by Django 5.1.7 on 2025-03-31 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shipments", "0013_remove_shipment_document_count"),
    ]

    operations = [
        migrations.RemoveField(model_name="customer", name="parcel",),
        migrations.RemoveField(model_name="parcel", name="customer_name",),
        migrations.RemoveField(model_name="shipment", name="customer_count",),
        migrations.RemoveField(model_name="shipment", name="parcel_count",),
    ]
