# Generated by Django 5.1.7 on 2025-03-31 22:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipments", "0015_document_invoice"),
    ]

    operations = [
        migrations.RemoveField(model_name="document", name="id",),
        migrations.AddField(
            model_name="document",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="shipments.customer",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="document",
            name="document_no",
            field=models.CharField(
                default="DOC0001", max_length=100, primary_key=True, serialize=False
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="issued_date",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="parcel",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="documents",
                to="shipments.parcel",
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("invoice", "Invoice"),
                    ("bill_of_lading", "Bill of Lading"),
                    ("customs_clearance", "Customs Clearance"),
                    ("packing_list", "Packing List"),
                    ("other", "Other"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="shipment",
            field=models.ForeignKey(
                db_column="shipment_no",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="shipments.shipment",
            ),
        ),
    ]
