# Generated by Django 5.1.7 on 2025-04-01 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipments", "0016_remove_document_id_document_customer_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="parcel",
            field=models.ForeignKey(
                blank=True,
                db_column="parcel_no",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="invoices",
                to="shipments.parcel",
            ),
        ),
    ]
