# Generated by Django 5.1.7 on 2025-04-01 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipments", "0017_alter_invoice_parcel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="parcel",
            field=models.ForeignKey(
                blank=True,
                db_column="parcel_no",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="documents",
                to="shipments.parcel",
            ),
        ),
    ]
