# Generated by Django 5.1.7 on 2025-04-01 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipments", "0018_alter_document_parcel"),
    ]

    operations = [
        migrations.AddField(
            model_name="shipment",
            name="volume_unit",
            field=models.CharField(
                choices=[("m³", "Cubic Meters"), ("ft³", "Cubic Feet")],
                default="m³",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="shipment",
            name="weight_unit",
            field=models.CharField(
                choices=[("kg", "Kilograms"), ("lbs", "Pounds"), ("tons", "Tons")],
                default="kg",
                max_length=10,
            ),
        ),
    ]
