# Generated by Django 5.1.7 on 2025-04-03 22:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipments", "0019_shipment_volume_unit_shipment_weight_unit"),
    ]

    operations = [
        migrations.RemoveField(model_name="parcel", name="commodity",),
        migrations.AddField(
            model_name="parcel",
            name="commodity_type",
            field=models.CharField(
                choices=[
                    ("box", "Box"),
                    ("parcel", "Parcel"),
                    ("envelope", "Envelope"),
                ],
                default="parcel",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="parcel",
            name="discription",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="parcel",
            name="volume_unit",
            field=models.CharField(
                choices=[("m³", "Cubic Meters"), ("ft³", "Cubic Feet")],
                default="m³",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="parcel",
            name="weight_unit",
            field=models.CharField(
                choices=[("kg", "Kilograms"), ("lbs", "Pounds"), ("tons", "Tons")],
                default="kg",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="shipment",
            field=models.OneToOneField(
                db_column="shipment_no",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invoices",
                to="shipments.shipment",
            ),
        ),
    ]
