# Generated by Django 5.1.7 on 2025-04-03 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipments", "0020_remove_parcel_commodity_parcel_commodity_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="email",
            field=models.EmailField(max_length=254),
        ),
    ]
